import { Geist, Geist_Mono } from "next/font/google";
import  "./script_CSS/style.css";
import UserProvider from "@/app/components/userContext";
import ChargerPanier from "@/app/components/chargerPanier";
import 'bootstrap-icons/font/bootstrap-icons.css';

import Script from "next/script";



import { CartProvider } from "@/app/components/panier";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&family=Lora:ital,wght@0,400..700;1,400..700&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet"/>
        

      </head>

      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{backgroundColor:""}}>
      <UserProvider>
      <CartProvider>
        
        <ChargerPanier/>
        {children}
      </CartProvider>
      </UserProvider>
      <Script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
  strategy="afterInteractive"
/>
       
      </body>
    </html>
  );
}
